/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_derycke_pieter_com_COMReference */

#ifndef _Included_be_derycke_pieter_com_COMReference
#define _Included_be_derycke_pieter_com_COMReference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_derycke_pieter_com_COMReference
 * Method:    release
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_derycke_pieter_com_COMReference_release
  (JNIEnv *, jobject);

/*
 * Class:     be_derycke_pieter_com_COMReference
 * Method:    addRef
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_be_derycke_pieter_com_COMReference_addRef
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
